Repository dolittle/JavaScript.SDK, pull requests merged in 2020-09, with the labels that each got.

#17 InScope and upartitioned options for @eventHandler decorator
  Samples/Environment/docker-compose.yml
  Samples/EventHorizon/MyEventHandler.ts
  Source/events.handling/EventHandler.ts
  Source/events.handling/EventHandlerDecoratedType.ts
  Source/events.handling/EventHandlerDecoratedTypes.ts
  Source/events.handling/EventHandlerId.ts
  Source/events.handling/EventHandlerOptions.ts
  Source/events.handling/EventHandlers.ts
  Source/events.handling/index.ts
  Source/events/EventStore.ts
  Source/events/ScopeId.ts
Labels: major

#18 Event type
  Samples/Basic/MyEvent.ts
  Samples/Container/MyEvent.ts
  Samples/EventHorizon/MyEvent.ts
  Source/artifacts/Artifact.ts
  Source/artifacts/index.ts
  Source/events/eventType.ts
  Source/events/index.ts
Labels: minor

#23 Trigger major version release
  Source/events/EventSourceId.ts
Labels: major

#24 Rename client building/configuring methods
  Samples/Basic/index.ts
  Samples/Container/index.ts
  Samples/EventHorizon/index.ts
  Source/artifacts/ArtifactId.ts
  Source/artifacts/ArtifactsBuilder.ts
  Source/artifacts/index.ts
  Source/eventHorizon/ConsentId.ts
  Source/eventHorizon/EventHorizons.ts
  Source/eventHorizon/SubscriptionBuilder.ts
  Source/eventHorizon/TenantWithSubscriptionsBuilder.ts
  Source/events.filtering/EventFilterBuilder.ts
  Source/events.filtering/EventFiltersBuilder.ts
  Source/events.filtering/FilterId.ts
  Source/events.filtering/PartitionedEventFilterBuilder.ts
  Source/events.filtering/PartitionedFilterResult.ts
  Source/events.filtering/PrivateEventFilterBuilder.ts
  Source/events.filtering/PublicEventFilterBuilder.ts
  Source/events.filtering/index.ts
  Source/events.handling/EventHandlersBuilder.ts
  Source/events/EventSourceId.ts
  Source/events/EventStoreBuilder.ts
  Source/events/PartitionId.ts
  Source/events/StreamId.ts
  Source/events/index.ts
  Source/execution/ExecutionContextManager.ts
  Source/execution/IExecutionContextManager.ts
  Source/execution/MicroserviceBuilder.ts
  Source/execution/for_ExecutionContextManager/when_getting_context_from_two_different_nested_async_contexts.ts
  Source/execution/index.ts
  Source/resilience/package.json
  Source/sdk/Client.ts
  Source/sdk/LoggingBuilder.ts
  Source/sdk/index.ts
  Source/services/ReverseCallClient.ts
Labels: major

#26 avoid recursive imports for index
  Source/sdk/Client.ts
  Source/sdk/index.ts
Labels: patch

#29 Remove execution context manager
  Samples/Basic/index.ts
  Samples/Container/index.ts
  Samples/EventHorizon/index.ts
  Source/eventHorizon/EventHorizons.ts
  Source/eventHorizon/EventHorizonsBuilder.ts
  Source/events.filtering/EventFiltersBuilder.ts
  Source/events.filtering/Internal/EventFilterProcessor.ts
  Source/events.filtering/Internal/FilterEventProcessor.ts
  Source/events.filtering/Internal/PartitionedEventFilterProcessor.ts
  Source/events.filtering/Internal/PublicEventFilterProcessor.ts
  Source/events.filtering/PartitionedEventFilterBuilder.ts
  Source/events.filtering/PrivateEventFilterBuilder.ts
  Source/events.filtering/PublicEventFilterBuilder.ts
  Source/events.filtering/UnpartitionedEventFilterBuilder.ts
  Source/events.handling/EventHandlers.ts
  Source/events.handling/EventHandlersBuilder.ts
  Source/events.handling/Internal/EventHandlerProcessor.ts
  Source/events.processing/Internal/EventProcessor.ts
  Source/events/EventStore.ts
  Source/events/EventStoreBuilder.ts
  Source/events/index.ts
  Source/execution/ExecutionContextExtensions.ts
  Source/execution/ExecutionContextManager.ts
  Source/execution/IExecutionContextManager.ts
  Source/execution/for_Dummy/when_nothing.ts
  Source/execution/for_ExecutionContextManager/when_getting_context_from_two_different_nested_async_contexts.ts
  Source/execution/index.ts
  Source/sdk/Client.ts
  Source/sdk/LoggingBuilder.ts
  Source/services/IReverseCallClient.ts
  Source/services/ReverseCallClient.ts
Labels: major
